name: End-to-end tests ðŸ§ª

on: deployment

jobs:
  regression:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v3
        with:
          name: Checkout the application repo ðŸ›Ž
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          repository: NaiaOzorio/the-words-that-i-know-end-to-end
          token: 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

          name: Install app dependencies ðŸ“¦
          uses: bahmutov/npm-install@v1

          name: Cypress run with env
          uses: cypress-io/github-action@v4
